# Generated by Django 3.0 on 2019-12-09 19:13

import backend.hotel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=40)),
                ('complement', models.CharField(max_length=60)),
                ('number', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('reviews_total', models.IntegerField(default=0)),
                ('reviews_average', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='auth_app.Business')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=backend.hotel.models.hotel_directory_path)),
                ('priority', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel.Hotel')),
            ],
        ),
    ]
