# Generated by Django 3.0 on 2019-12-09 19:13

import backend.room.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('reviews_count', models.IntegerField(default=0)),
                ('reviews_total', models.IntegerField(default=0)),
                ('reviews_average', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.Hotel')),
                ('productList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='product.ProductList')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=backend.room.models.room_directory_path)),
                ('priority', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rooms', models.ManyToManyField(related_name='amenities', to='room.Room')),
            ],
        ),
    ]
