# Generated by Django 3.0.1 on 2020-01-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200108_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.Review'),
        ),
    ]
