# Generated by Django 3.0.1 on 2020-01-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200109_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.Review'),
        ),
    ]
